//import './stylesheets/video2.css';
import './views/videoFlexTab2.html';
import './views/videoFlexTab2';
import './tabBar';
import './actionLink';
import '../lib/messageType';
import './JitsiCall'
import './adapter'
import './jitsiCall.css'
